DRAFT
pagarme/node-boleto pull request #39
Opened 2020-12-01 13:40 UTC by alinemarjorie

2020-12-01 14:05 UTC, alinemarjorie commented on banks/caixa/index.js
> +        parsedFile['data_arquivo'] = ediHelper.dateFromEdiDate(line.substring(99, 105))
Essa parte aqui foi a única que deu diferença entre a docs e o EDI file da Mundi... Segui com a posição do EDI file

2020-12-01 14:10 UTC, Thor99 requested changes

2020-12-01 14:10 UTC, Thor99 commented on banks/caixa/index.js
> +      if (registro === '0') {
quando é 0 é tipo uma linha de header, é isso?

2020-12-01 14:10 UTC, Thor99 commented on banks/caixa/index.js
> +    console.log(e)
o padrão é usar console.log no node-boleto msm (e não um logger da vida)?

2020-12-01 14:10 UTC, Thor99 commented on lib/edi-helper.js
> +  return new Date(parseInt('20' + ediDate.substring(4, 8)), parseInt(ediDate.substring(2, 4)) - 1, parseInt(ediDate.substring(0, 2)))
Sugestão: Dividir as informações de dia, mes, ano que ta dentro do `New Date()` em variáveis, e passar pro new Date, para melhorar legibilidade

2020-12-01 14:10 UTC, Thor99 commented on test/integration/caixa/edi.spec.js
> +      console.log(result)
consologou em teste :thinking: :rotating_light:

2020-12-01 14:10 UTC, Thor99 commented on test/integration/caixa/edi.spec.js
> +      console.log('boletooo 2', boleto)
:rotating_light:

2020-12-01 14:12 UTC, alinemarjorie commented on test/integration/caixa/edi.spec.js
> +      console.log(result)
AHHHHHHHHHHHHHHH

2020-12-01 14:12 UTC, alinemarjorie commented on test/integration/caixa/edi.spec.js
> +      console.log('boletooo 2', boleto)
prontooooo

2020-12-01 14:19 UTC, alinemarjorie commented on banks/caixa/index.js
> +    console.log(e)
É o padrão do node-boleto sim, como eu peguei o do Bradesco como base, está igual.

2020-12-01 14:25 UTC, alinemarjorie commented on banks/caixa/index.js
> +      if (registro === '0') {
Isso mesmo Thor! Pelo o que vi nas docs da caixa e do Bradesco, eles separam o header do detalhes(boletos) por esse código mesmo. 
0 header
1 detalhe

2020-12-01 14:34 UTC, alinemarjorie commented on lib/edi-helper.js
> +  return new Date(parseInt('20' + ediDate.substring(4, 8)), parseInt(ediDate.substring(2, 4)) - 1, parseInt(ediDate.substring(0, 2)))
Prontin! :D

2020-12-01 16:13 UTC, lucianopf commented on banks/caixa/index.js
> +      } else if (registro === '1') {
Ele só tem `if` e `else if`, não tem `else` não? 👀

2020-12-01 16:14 UTC, lucianopf commented on banks/caixa/index.js
> +    console.log(e)
O ideal mesmo era subir o erro pra quem invocou a função, mas entendo que devemos seguir como a outra implementação 😬

2020-12-01 16:15 UTC, lucianopf approved these changes
P.B.P.M

2020-12-01 16:16 UTC, Thor99 approved these changes

2020-12-01 16:16 UTC, Thor99 commented on banks/caixa/index.js
> +      } else if (registro === '1') {
lintão do core ia ficar em choque kk

2020-12-01 16:26 UTC, alinemarjorie commented on banks/caixa/index.js
> +      } else if (registro === '1') {
Só tem cenário pro 0 e 1 mesmo

2020-12-01 16:55 UTC, 0xkalvin commented on banks/caixa/index.js
> +    console.log(e)
Totalmente opcional: Se fizer sentido, como alternativa também daria pra usar 
```javascript
console.error(e)
```
Que ajuda a diferenciar logs de erros de outros

2020-12-01 16:55 UTC, 0xkalvin approved these changes

2020-12-01 18:07 UTC, matheuslcandido approved these changes

2020-12-01 20:00 UTC, igorantun approved these changes

2020-12-01 23:58 UTC, lucianopf commented
🏷️ 🏷️ 🏷️ 🏷️ 🏷️ 
 @igorantun 
🏷️ 🏷️ 🏷️ 🏷️ 🏷️

2020-12-02 20:00 UTC, lucianopf approved these changes

2020-12-02 20:01 UTC, merged